data:
  rna_path: "./data/perturb_processed.h5ad"       # Path to the processed single-cell data
  embedding_path: "data/GenePT_emebdding_v2/GenePT_gene_protein_embedding_model_3_text.pickle."  # Path to the gene embedding file
  pca: True                   # Whether to use PCA
  num_pc: 100                 # Number of principal components to use
  regre: False                # Whether to use regression to fit the embeddings
  split_ratio: 0.8, 0.1, 0.1  # Ratio of Training/validation/test set
  norm_sum: 1000              # Normalization factor for Scanpy preprocessing
  num_HVG: 1000               # Number of highly variable genes to use

training:
  batch_size: 64
  num_workers: 0
  num_epochs: 200
  lr: 1e-4
  weight_decay: 1e-4
  scheduler: "cosine"
  device: "cuda"             # "cpu", "cuda"
  seed: 42                   # mainly used for the random pairing,
  save_every: 50             # Save the model every n epochs

model:
  gene_dim: 5060            
  embedding_dim: 3072     
  hidden_dims: [256, 512, 256] 
  time_emb_dim: 1024
  dropout: 0.1        
  diffusion_steps: 100       # Number of denoising steps

dir:
  save_dir: "./Diff_pert/results"
  checkpoint_dir: "./Diff_pert/results/checkpoints"
  pred_dir: "./Diff_pert/results/predictions"
  verbose: True